# Generated by Django 6.0.2 on 2026-02-27 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid 10-digit Indian phone number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
