# Generated by Django 6.0.2 on 2026-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_created_at_alter_note_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
